fun main(){
    //Library Membership Form

    //Personal Profile
    var firstName:String = "Mary Claire"
    var middleName:String = "Ballesteros"
    var lastName:String = "Osongco"
    var address:String = "Pagbilao Quezon"
    var email:String = "maryclaireosongco@gmail.com"
    var sex:String = "Female"
    var contactNumber:Long = 9928310994
    var localGuardiansName:String = "Eduardo Osongco"
    var relationship:String = "Father"
    var guardiansAddress:String = "Pagbilao Quezon"
    var guardiansContact:Long = 9931234567
    var deptOrProgram:String = "IT"
    var idNumber:Int = 366919
    var semester:String = "First Semester"
    var year:Int = 2023
    var batch:String = "MP5P"
    var studentsSignature:String = ""
    var dateSigned:String = ""
    //For Official Use Only
    var libraryCardNumber:Int = 123456
    var validUpTo:String = ""
    //Received Library Cards.
    //Student's Signature     Issued by       Librarian

    //Books Categories
    //Fiction
    var actionAndAdventures1:String = "Title1"
    var actionAndAdventures2:String = "Title2"
    var actionAndAdventures3:String = "Title3"
    var anthology1:String = "Title1"
    var anthology2:String = "Title2"
    var anthology3:String = "Title3"
    var childrens1:String = "Title1"
    var childrens2:String = "Title2"
    var childrens3:String = "Title3"
    var classic1:String = "Title1"
    var classic2:String = "Title2"
    var classic3:String = "Title3"
    var comicBook1:String = "Title1"
    var comicBook2:String = "Title2"
    var comicBook3:String = "Title3"
    var crime1:String = "Title1"
    var crime2:String = "Title2"
    var crime3:String = "Title3"
    var drama1:String = "Title1"
    var drama2:String = "Title2"
    var drama3:String = "Title3"
    var fairytale1:String = "Title1"
    var fairytale2:String = "Title2"
    var fairytale3:String = "Title3"
    var fantasy1:String = "Title1"
    var fantasy2:String = "Title2"
    var fantasy3:String = "Title3"
    var graphicNovel1:String = "Title1"
    var graphicNovel2:String = "Title2"
    var graphicNovel3:String = "Title3"
    var historicalFiction1:String = "Title1"
    var historicalFiction2:String = "Title2"
    var historicalFiction3:String = "Title3"
    var horror1:String = "Title1"
    var horror2:String = "Title2"
    var horror3:String = "Title3"
    var mystery1:String = "Title1"
    var mystery2:String = "Title2"
    var mystery3:String = "Title3"
    var poetry1:String = "Title1"
    var poetry2:String = "Title2"
    var poetry3:String = "Title3"
    var politicalThriller1:String = "Title1"
    var politicalThriller2:String = "Title2"
    var politicalThriller3:String = "Title3"
    var romance1:String = "Title1"
    var romance2:String = "Title2"
    var romance3:String = "Title3"
    var scienceFiction1:String = "Title1"
    var scienceFiction2:String = "Title2"
    var scienceFiction3:String = "Title3"
    var shortStory1:String = "Title1"
    var shortStory2:String = "Title2"
    var shortStory3:String = "Title3"
    var youngAdult1:String = "Title1"
    var youngAdult2:String = "Title2"
    var youngAdult3:String = "Title3"

    //Nonfiction
    var artArchitecture1:String = "Title1"
    var artArchitecture2:String = "Title2"
    var artArchitecture3:String = "Title3"
    var autobiography1:String = "Title1"
    var autobiography2:String = "Title2"
    var autobiography3:String = "Title3"
    var businessEconomics1:String = "Title1"
    var businessEconomics2:String = "Title2"
    var businessEconomics3:String = "Title3"
    var craftsHobbies1:String = "Title1"
    var craftsHobbies2:String = "Title2"
    var craftsHobbies3:String = "Title3"
    var cookBook1:String = "Title1"
    var cookBook2:String = "Title2"
    var cookBook3:String = "Title3"
    var dictionary1:String = "Title1"
    var dictionary2:String = "Title2"
    var dictionary3:String = "Title3"
    var encyclopedia1:String = "Title1"
    var encyclopedia2:String = "Title2"
    var encyclopedia3:String = "Title3"
    var healthFitness1:String = "Title1"
    var healthFitness2:String = "Title2"
    var healthFitness3:String = "Title3"
    var history1:String = "Title1"
    var history2:String = "Title2"
    var history3:String = "Title3"
    var homeAndGarden1:String = "Title1"
    var homeAndGarden2:String = "Title2"
    var homeAndGarden3:String = "Title3"
    var math1:String = "Title1"
    var math2:String = "Title2"
    var math3:String = "Title3"
    var philosophy1:String = "Title1"
    var philosophy2:String = "Title2"
    var philosophy3:String = "Title3"
    var religion1:String = "Title1"
    var religion2:String = "Title2"
    var religion3:String = "Title3"
    var science1:String = "Title1"
    var science2:String = "Title2"
    var science3:String = "Title3"
    var sportsAndLeisure1:String = "Title1"
    var sportsAndLeisure2:String = "Title2"
    var sportsAndLeisure3:String = "Title3"
    var travel1:String = "Title1"
    var travel2:String = "Title2"
    var travel3:String = "Title3"


}